title: Поездка в Санкт-Петербург
author: RayRaf
email: joao@neto.pt
description: >-
  Интересная поездка в Санкт-Петербург
  

social:
  twitter: joaomlneto
  facebook: joaomlneto
  instagram: joaomlneto
  github: joaomlneto
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
